<a href="https://colab.research.google.com/github/mihitkeshav/Linear-Regression-Implmenatation/blob/master/scipy_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files

In [3]:
files.upload()

Saving clusterincluster.txt to clusterincluster (1).txt


{'clusterincluster.txt': b'0.61532 -1.1072 0\r\n-0.80069 0.59908 0\r\n-0.70984 0.70436 0\r\n0.59479 1.1183 0\r\n0.41828 -0.90832 0\r\n1.2763 -0.84987 0\r\n0.67615 -1.3762 0\r\n0.67508 -1.3767 0\r\n0.21832 -1.2477 0\r\n0.99687 0.079042 0\r\n0.011176 1.5333 0\r\n0.54064 -0.84125 0\r\n1.0489 -0.71014 0\r\n-1.2157 -0.35554 0\r\n-0.84012 -0.5424 0\r\n-0.54668 1.1426 0\r\n-1.5261 -0.14849 0\r\n-1.5046 0.29528 0\r\n0.38975 -0.92092 0\r\n-1.5237 -0.17133 0\r\n-0.59222 0.80578 0\r\n-0.20938 -1.2492 0\r\n0.83787 0.94996 0\r\n0.015843 -0.99987 0\r\n1.4756 0.4167 0\r\n-0.75487 1.0172 0\r\n0.93667 0.8527 0\r\n-0.38581 1.2065 0\r\n-0.59106 -0.80663 0\r\n-0.96614 0.25803 0\r\n1.2115 0.93993 0\r\n0.19407 -1.521 0\r\n0.35699 -0.93411 0\r\n1.1782 0.46499 0\r\n1.1356 0.56105 0\r\n1.2667 0.0004329 0\r\n0.58275 1.1247 0\r\n1.2197 -0.92923 0\r\n-0.30317 0.95294 0\r\n-0.72619 0.68749 0\r\n-0.98071 -0.19547 0\r\n-0.78733 0.61653 0\r\n-1.1981 -0.41104 0\r\n1.5253 -0.15664 0\r\n-0.97123 0.81311 0\r\n-0.25295 0.

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:

df = pd.read_csv('clusterincluster.txt', sep=" ",header=None)
X = df.iloc[:,0:2]
y = df.iloc[:,2]
df.head()

0        1  2
0  0.61532 -1.10720  0
1 -0.80069  0.59908  0
2 -0.70984  0.70436  0
3  0.59479  1.11830  0
4  0.41828 -0.90832  0

In [15]:
df.count()

0    4996
1    4996
2    4996
dtype: int64

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)


In [0]:
from sklearn.linear_model import LogisticRegression

In [18]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [19]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[354, 270],
       [333, 292]])

In [22]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)


Accuracy: 51.72137710168134


In [23]:
files.upload()

Saving DoubleMoon2.txt to DoubleMoon2.txt


{'DoubleMoon2.txt': b'-0.54228,4.6484,0\n5.1505,0.43904,0\n2.277,4.3406,0\n3.6047,3.5748,0\n-4.7841,1.8821,0\n4.6398,0.2559,0\n-2.5593,4.3721,0\n-3.5044,3.5581,0\n-5.0223,1.7639,0\n1.3164,4.4763,0\n-3.4487,3.8411,0\n-4.4472,1.1768,0\n5.139,1.3531,0\n-3.9082,2.6349,0\n-0.30206,4.6798,0\n3.9982,3.2928,0\n-3.2762,3.1766,0\n-4.3626,2.6046,0\n-1.8333,5.1247,0\n4.1844,3.0838,0\n-3.0123,4.419,0\n-3.8856,3.712,0\n3.7433,2.8735,0\n4.6434,2.5278,0\n-3.7829,3.6759,0\n-3.1351,4.1999,0\n-1.3074,4.8397,0\n4.6182,2.3145,0\n-3.3029,3.8745,0\n3.4289,4.2771,0\n-2.9152,3.7593,0\n-3.5798,3.8356,0\n-0.89687,5.4052,0\n-1.0382,5.3078,0\n3.2126,4.2108,0\n4.6537,0.71913,0\n0.32461,5.3298,0\n-3.0583,4.1426,0\n3.6088,2.8988,0\n0.31861,4.6511,0\n4.362,2.3562,0\n4.5934,0.68692,0\n3.2076,3.4641,0\n4.3425,1.9021,0\n5.0044,0.85746,0\n5.0364,0.99188,0\n4.3814,1.6393,0\n4.6015,2.1169,0\n-3.5277,4.0638,0\n3.8836,3.0823,0\n0.5427,5.3189,0\n-1.9742,4.8843,0\n0.17741,4.739,0\n-1.606,4.5309,0\n-3.2725,3.1908,0\n-4.5838,0.12

In [25]:
df = pd.read_csv('DoubleMoon2.txt',header=None)
X = df.iloc[:,0:2]
y = df.iloc[:,2]
df.head()

0        1  2
0 -0.54228  4.64840  0
1  5.15050  0.43904  0
2  2.27700  4.34060  0
3  3.60470  3.57480  0
4 -4.78410  1.88210  0

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [0]:
from sklearn.linear_model import LogisticRegression

In [28]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [29]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[1263,    0],
       [   0, 1237]])

In [30]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 100.0


In [31]:
files.upload()

Saving Image3.txt to Image3.txt


{'Image3.txt': b'2.1668,5.4895,1\n-1.9563,-0.79647,1\n1.7243,1.3583,1\n4.5019,6.0332,1\n0.7053,4.1696,1\n2.6704,3.8539,1\n1.7692,3.4003,1\n0.16697,1.2728,1\n1.0363,2.4102,1\n1.8296,3.3021,1\n2.5091,4.6331,1\n2.064,3.5895,1\n-0.12058,0.41275,1\n0.019666,2.2576,1\n0.036219,2.0027,1\n2.9062,4.8533,1\n-2.7122,-1.7064,1\n-1.571,1.1396,1\n0.45022,0.86376,1\n0.91464,4.703,1\n-2.6071,0.0090352,1\n-0.50713,0.34227,1\n1.0772,1.8225,1\n4.1019,5.0319,1\n2.6588,3.9888,1\n1.504,1.9979,1\n0.42564,2.4996,1\n0.26602,2.2607,1\n1.6399,3.6221,1\n2.592,4.2995,1\n2.7495,5.6385,1\n0.39314,2.9002,1\n1.4192,1.7646,1\n2.9976,3.4984,1\n0.21799,3.389,1\n-0.69489,0.81694,1\n-0.26374,0.57647,1\n-1.0715,1.9523,1\n-0.76887,2.0119,1\n2.5695,3.3576,1\n0.6385,1.5843,1\n2.2721,4.5004,1\n1.0856,2.6816,1\n-1.0377,1.5012,1\n1.7945,5.2148,1\n2.7094,3.5203,1\n0.27072,2.2491,1\n-0.58945,2.1986,1\n-3.5185,-0.052164,1\n-0.32045,2.7968,1\n2.289,4.5971,1\n1.5531,1.3641,1\n0.5685,2.5053,1\n2.2084,3.8858,1\n1.4643,3.1777,1\n-0.07959

In [32]:
df = pd.read_csv('Image3.txt',header=None)
X = df.iloc[:,0:2]
y = df.iloc[:,2]
df.head()

0        1  2
0  2.1668  5.48950  1
1 -1.9563 -0.79647  1
2  1.7243  1.35830  1
3  4.5019  6.03320  1
4  0.7053  4.16960  1

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [34]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [35]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[1262,    1],
       [   1, 1236]])

In [36]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 99.92


In [37]:
files.upload()

Saving Moon.txt to Moon.txt


{'Moon.txt': b'-2.9427,3.5878,0\n1.1986,1.2473,0\n1.4453,0.94387,0\n2.5198,3.85,0\n3.3139,-2.5384,0\n-3.386,1.0913,0\n3.385,-0.14871,0\n1.7762,2.0934,0\n-2.8435,2.9787,0\n-4.699,-1.4026,0\n-2.7364,1.0436,0\n2.0161,1.0174,0\n-1.5726,2.645,0\n0.90138,4.432,0\n2.0879,2.6499,0\n0.8725,-0.18077,0\n2.427,-4.191,0\n2.5265,-1.9343,0\n-0.75493,-0.25503,0\n-2.7902,1.6697,0\n-2.2518,-0.62691,0\n-3.4715,1.6756,0\n-3.8662,0.63576,0\n3.4646,-0.49608,0\n3.9633,1.8148,0\n-4.0224,-2.1824,0\n2.0487,1.2278,0\n-0.50503,4.8029,0\n-1.1983,-0.83222,0\n2.4507,-1.0229,0\n-0.089376,-2.8221,0\n-0.26336,2.4775,0\n-1.522,2.6274,0\n-0.46134,0.30624,0\n2.9771,-1.1558,0\n4.7421,-0.62358,0\n2.8811,2.4219,0\n0.26605,1.7149,0\n-0.39639,-3.5353,0\n1.3212,1.6227,0\n-0.73215,-2.7402,0\n-2.9575,3.2798,0\n-4.4729,2.142,0\n2.5986,-1.9071,0\n-0.55233,1.147,0\n1.3541,-2.2026,0\n4.7047,1.4839,0\n-1.4663,-1.8598,0\n-1.4378,3.1872,0\n-4.0383,-2.3344,0\n-3.6062,-1.5685,0\n2.7553,1.8822,0\n-0.18702,0.042696,0\n-2.8271,-0.81663,0\n-0

In [38]:
df = pd.read_csv('Moon.txt',header=None)
X = df.iloc[:,0:2]
y = df.iloc[:,2]
df.head()

0        1  2
0 -2.9427  3.58780  0
1  1.1986  1.24730  0
2  1.4453  0.94387  0
3  2.5198  3.85000  0
4  3.3139 -2.53840  0

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)


In [40]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [41]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[ 33,  16],
       [ 16, 185]])

In [42]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100)


Accuracy: 87.2
